#!/bin/bash
basepath="gitrepos/"
repo=$(basename `pwd`)

if [[ $(uname) == "Linux" ]]  ; then
    for vol in $(ls -1 /media/) ; do 
        target_path="$vol" "/$basepath" "/$repo.git"
        if [[ -d $target_path ]] ; then
            git push $target_path
        else
            mkdir $target_path
            git init --bare $target_path
            git push $target_path
        fi
    done
elif [[ $(uname) == "Darwin" ]] ; then


fi
